default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tsundoku_breaker_development

test:
  <<: *default
  database: tsundoku_breaker_test

production:
  primary: &primary_production
    <<: *default
    database: tsundoku_breaker_production
    username: tsundoku_breaker
    password: <%= ENV["TSUNDOKU_BREAKER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tsundoku_breaker_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tsundoku_breaker_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tsundoku_breaker_production_cable
    migrations_paths: db/cable_migrate